### ISSUE TITLE
Add app memory usage

### ISSUE THREAD

**Issue by MKGitHub** [dani-gavrilov/GDPerformanceView-Swift#1]
Add app memory usage

**Comment by dani-gavrilov** [comment]
Hello,
I'm planning to add this feature, but currently i don't have enough free time. 

Thank you for using GDPerformanceView.

**Comment by dani-gavrilov** [comment]
Recently I tested memory usage in obj-c version of GDPerformanceView. And I decided that memory usage isn't related to performance. Lets try to keep PerformanceView as light as possible.

**Comment by DanielAsher** [comment]
I would like to reopen this request. Memory leaks are very easy to create, not so easy to spot until later. Having a total memory used would allow testers to quickly spot and report.

**Comment by DanielAsher** [comment]
Thanks for a great framework!

**Comment by dani-gavrilov** [comment]
You convinced me. I will add this next week, but I think that it would be better if it stays turned off by default.

**Comment by dani-gavrilov** [comment]
It was the longest week of my life :P
Please, check out the latest release.
