### ISSUE TITLE
Calling stopMonitoring doesn't prevent monitor from restarting automatically upon resuming from the background.

### ISSUE THREAD

**Issue by lemonkey** [dani-gavrilov/GDPerformanceView-Swift#10]
Temporary fix is to also call pauseMonitoring before calling stopMonitoring.

**Comment by dani-gavrilov** [comment]
Please, check out new version [GDPerformanceView-Swift 1.2.0](https://github.com/dani-gavrilov/GDPerformanceView-Swift).

I apologize for the long wait.
