### ISSUE TITLE
Swift 3.1 Error

### ISSUE THREAD

**Issue by maurovc** [dani-gavrilov/GDPerformanceView-Swift#12]
Solved by deleting the ! but new pod version needed.

<img width="1247" alt="screen shot 2017-03-28 at 11 05 26 2" src="https://cloud.githubusercontent.com/assets/10012427/24397493/ae4cc15a-13a6-11e7-93be-8a3e310bae73.png">

**Comment by lemonkey** [comment]
+1

**Comment by dani-gavrilov** [comment]
Please, check out new version [GDPerformanceView-Swift 1.2.0](https://github.com/dani-gavrilov/GDPerformanceView-Swift).

**Comment by lemonkey** [comment]
Thanks!
