### ISSUE TITLE
How is the fps measured?

### ISSUE THREAD

**Issue by multinerd** [dani-gavrilov/GDPerformanceView-Swift#13]
Is it measured the same way [WatchdogInspector](https://github.com/tapwork/WatchdogInspector#how-it-works) measures fps or is it done differently?

**Comment by dani-gavrilov** [comment]
Hello.
GDPerformanceView uses CADisplayLink to get frame rate. https://developer.apple.com/documentation/quartzcore/cadisplaylink

By quick look, WatchdogInspector uses the different ways.
