### ISSUE TITLE
swift 4 !!!!!!!

### ISSUE THREAD

**Issue by lixiang1994** [dani-gavrilov/GDPerformanceView-Swift#16]

**Comment by lemonkey** [comment]
FYI, a quick fix to support Swift 4 would be to add @objcMembers before the GDPerformanceMonitor class definition:

```
@objcMembers
public class GDPerformanceMonitor: NSObject { ... }
```

**Comment by dani-gavrilov** [comment]
Please, check the lates version. It should be fixed.
