### ISSUE TITLE
Add custom info

### ISSUE THREAD

**Issue by jeryTymate** [dani-gavrilov/GDPerformanceView-Swift#17]
Is it possible to add custom info info in the performance view?

For example, I would like to add the date when the user started the application.

Thank you a lot !

**Comment by dani-gavrilov** [comment]
Hello. 
I this this is possible. I will try to implement this in a few days.

**Comment by dani-gavrilov** [comment]
Starting with 2.0.2 you can use the following:
self.performanceView?.performanceViewConfigurator.userInfo = .custom(string: "Launch date \(Date())")
