### ISSUE TITLE
Detect tap

### ISSUE THREAD

**Issue by jeryRazakarison** [dani-gavrilov/GDPerformanceView-Swift#18]
Is it possible to detect a tap on the performance view? I would like to do a custom action when the user taps on it.

Thank you very much

**Comment by dani-gavrilov** [comment]
Hello. It is not designed for user interactions. Are you using it in productions or you need this for development / testing purposes?

I will see what can I do later this week.

**Comment by dani-gavrilov** [comment]
Starting with 2.0.2 you can do the following:
self.performanceView?.performanceViewConfigurator.interactors = [tapGesture, swipeGesture]
