### ISSUE TITLE
Need some example to add to my app

### ISSUE THREAD

**Issue by githotto** [dani-gavrilov/GDPerformanceView-Swift#3]
Using the pod-file and updating my project given the example is fairly easy, but I'm missing instructions on how to get it running?!
I tried adding the start-monitoring to my AppDelegate.swift

`private func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.
}`

and the stop-monitoring to my AppDelegate.swift

`func applicationWillTerminate(_ application: UIApplication) {
        // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
        gdpMonitoringStop()
    }`

but getting compile-errors.
Do I need to add 'import GDPMonitoring' after 'import UIKit' in my AppDelegate.swift ?

**Comment by dani-gavrilov** [comment]
Hello,
You should write 'import GDPerformanceView_Swift' if you are using CocoaPods.

With last release you can also use Carthage 'github "dani-gavrilov/GDPerformanceView-Swift" ~> 1.0.4' and write 'import GDPerformanceView'.

Feel free to contact me in case of any problems with framework. Thank you for using GDPerformanceView.

**Comment by githotto** [comment]
Hi Dani,
Thanks for the reply, which solved part of my problems.
Still having compiler errors while adding:
`GDPerformanceMonitor.sharedInstance.startMonitoring()
        self.performanceView = GDPerformanceMonitor.init()
        self.performanceView?.startMonitoring()`
to my AppDelegate.application(..) method.
It complains with: 'type of AppDelegate has no member performanceView'

Should I add something like:
`var performanceMonitor: GDPerformanceMonitor?
performanceMonitor = GDPerformanceMonitor.sharedInstance`

or do you perhaps have a mini-example (based a e.g. a new SIngleView project) in which I can see more clearly where you need to add the above import, start/stop-monitoring code?
Thanks in advance, kind regards.

**Comment by dani-gavrilov** [comment]
Yes, you should add 'var performanceMonitor: GDPerformanceMonitor?'

You can download or clone all project. There you can find example of usage, but it is not what we can call 'example project'.
I will reopen issue and add example projects for CocoaPods and Carthage soon.

**Comment by dani-gavrilov** [comment]
Example-Carthage and Example-CocoaPods were added to the repository. You can clone or download them and take a closer look.
