### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by TofPlay** [dani-gavrilov/GDPerformanceView-Swift#4]
Hi,
For iOS projets it's will be great to make your component [Carthage](https://github.com/Carthage/Carthage) compatible

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://bit.ly/2IWvGks)
- [Carthage Tutorial: Getting Started](https://bit.ly/2zes4dN)
- [Making Carthage-compatible Frameworks with Swift](https://bit.ly/2tXUofp)
- [Swift Cross Platform Framework](https://bit.ly/2ysgETA) (section [Configure targets for Carthage](https://bit.ly/2tZUOSt)) 👍

On your `README.md` add [![Carthage compatible](https://img.shields.io/badge/Carthage-Compatible-brightgreen.svg?style=flat)](https://github.com/Carthage/Carthage)  on top and add section for the installation with Carthage.

**Comment by dani-gavrilov** [comment]
Hello, you can check out new release with 'github "dani-gavrilov/GDPerformanceView-Swift" ~> 1.0.4' via Carthage.

Thank you for using GDPerformanceView.

I will change my README later as suggested in https://github.com/dani-gavrilov/GDPerformanceView-Swift/issues/5
