### ISSUE TITLE
iOS 9 status bar style "lightContent" not working

### ISSUE THREAD

**Issue by 1024kilobyte** [dani-gavrilov/GDPerformanceView-Swift#8]
Now that the status bar is visible on iOS 9 I recognized that the status bar style set by the  view controller is ignored. My code is pretty simple:

`
override var prefersStatusBarHidden: Bool {
    return false
}
    
override var preferredStatusBarStyle: UIStatusBarStyle {
    return isDarkMode ? .lightContent : .default
}
`

The status bar style is switching on iOS 10 but not on iOS 9 (where it is always default).

**Comment by dani-gavrilov** [comment]
Take a look at release v1.0.9. 

It seems that the only way to fix this is configure status bar of GDPerformanceVIew root view controller. So now you can use something like this - 'GDPerformanceMonitor.sharedInstance.configureStatusBarAppearance(prefersStatusBarHidden: false, preferredStatusBarStyle: UIStatusBarStyle.lightContent)'
